version: '3.7'

services:

  # ZooKeeper
  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    hostname: zookeeper
    networks:
      - flowing
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  # Kafka
  kafka:
    image: "confluentinc/cp-kafka:latest"
    hostname: kafka
    networks:
      - flowing
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
  # Services
  shop:
    build: shop
    networks:
      - flowing
    ports:
      - "8090:8090"
    depends_on:
      - kafka
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES=kafka:2181

  order:
    build: order-camunda
    networks:
      - flowing
    ports:
      - "8091:8091"
    depends_on:
      - kafka
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES=kafka:2181

  payment:
    build: payment-camunda
    networks:
      - flowing
    ports:
      - "8092:8092"
    depends_on:
      - kafka
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES=kafka:2181

  inventory:
    build: inventory
    networks:
      - flowing
    depends_on:
      - kafka
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES=kafka:2181

  shipping:
    build: shipping
    networks:
      - flowing
    depends_on:
      - kafka
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES=kafka:2181

  # Monitor
  monitor:
    build: monitor
    networks:
      - flowing
    ports:
      - "8095:8095"
    depends_on:
      - kafka
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES=kafka:2181

networks:
  flowing:
    driver: bridge
